# Generated by Django 2.1.5 on 2020-04-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
