# Generated by Django 2.1.5 on 2020-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200421_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='a',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='b',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
